baseURL = 'http://cest.se/'
languageCode = 'en-us'
theme = 'graysx'
title = 'CEST'

## Site Settings
[params]
logo = "/assets/img/CEST-logo-simple-white.png"
favicon = "/assets/favicon.png"
footer_logo = "/assets/img/vinnova_green_payoff_rgb.png"

# Info
address = "123 Arch B1W, GNU/Linux"
email = "cest@cest.com"
phone = "123456"

# Socials

twitter = "#"
facebook = "#"
github = "#"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "Home"
  URL = "/"
  weight = 1
  identifier = "about"

  [[menu.main]]
  name = "Solution"
  URL = "/solution"
  weight = 3

  [[menu.main]]
  name = "Resources"
  URL = "/articles"
  weight = 4

 [[menu.main]]
  name = "Consortium"
  URL = "/consortium"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "/contact"
  weight = 5
  
# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04
