baseURL = 'http://cest.se/'
languageCode = 'en-us'
title = 'CEST'
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
custom_css = ["custom.css"]
site_logo = "images/logowhite.png"
