baseURL = 'http://cest.se/'
languageCode = 'en-us'
theme = 'graysx'
title = 'CEST'

## Site Settings
[params]
logo = "/assets/img/CEST-logo-simple-white.png"
favicon = "/assets/favicon.png"
footer_logo = "/assets/img/Vinnova_white_payoff_RGB.png"

# Info
address = "123 Arch B1W, GNU/Linux"
email = "cest@cest.com"
phone = "123456"

# Socials

twitter = "#"
facebook = "#"
github = "#"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "/about"
  weight = 1
  identifier = "about"

  [[menu.main]]
  name = "Vision"
  URL = "/vision"
  weight = 2

  [[menu.main]]
  name = "Articles"
  URL = "/articles"
  weight = 3

 [[menu.main]]
  name = "Consortium"
  URL = "/#consortium"
  weight = 5

  [[menu.main]]
  name = "Contact"
  URL = "/#contact"
  weight = 6
  
  [[menu.main]]
  name = "Story"
  URL = "/story"
  weight = 4


# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04
